"""Generates rust/src/shapes.rs from the checkpoint fixtures.

The embedded coordinates are the Python-normalized boundary vertices, emitted
as shortest-round-trip decimal literals, so the Rust polygons are bit-identical
to the shapely ones. Run after (re)generating fixtures:

    .venv-fixtures/bin/python rust/fixtures/gen_shapes_rs.py
"""

import json
import os

OUT_DIR = os.path.dirname(os.path.abspath(__file__))
SHAPES = ["shape_a", "shape_b", "shape_c", "shape_duck"]

HEADER = '''\
//! Floor-plan boundary shapes, mirroring `shape.py`'s normalized output:
//! coordinates centered on their mean and scaled by the max vertex norm.
//!
//! GENERATED by fixtures/gen_shapes_rs.py from the Python golden fixtures —
//! the literals are exact (shortest-round-trip) copies of the f64 vertices
//! shapely produced. Do not edit by hand.

use geo::{LineString, Polygon};

pub struct Shape {
    pub name: &'static str,
    pub boundary: Vec<[f64; 2]>,
}

impl Shape {
    pub fn polygon(&self) -> Polygon<f64> {
        Polygon::new(
            LineString::from(
                self.boundary
                    .iter()
                    .map(|&[x, y]| (x, y))
                    .collect::<Vec<_>>(),
            ),
            vec![],
        )
    }
}

pub const SHAPE_NAMES: [&str; 4] = ["shape_a", "shape_b", "shape_c", "shape_duck"];
'''


def lit(v):
    s = repr(float(v))
    if "." not in s and "e" not in s and "inf" not in s and "nan" not in s:
        s += ".0"
    return s


def main():
    consts = []
    arms = []
    for name in SHAPES:
        with open(os.path.join(OUT_DIR, f"{name}.checkpoint.json")) as f:
            coords = json.load(f)["shape"]["boundary_coords"]
        rows = ",\n    ".join(f"[{lit(x)}, {lit(y)}]" for x, y in coords)
        const_name = name.upper()
        consts.append(f"const {const_name}: [[f64; 2]; {len(coords)}] = [\n    {rows},\n];\n")
        arms.append(f'        "{name}" => Some(Shape {{ name: "{name}", boundary: {const_name}.to_vec() }}),')

    body = "\n".join(consts)
    match_arms = "\n".join(arms)
    func = (
        "\npub fn by_name(name: &str) -> Option<Shape> {\n"
        "    match name {\n"
        f"{match_arms}\n"
        "        _ => None,\n"
        "    }\n"
        "}\n"
    )

    out = os.path.join(OUT_DIR, "..", "src", "shapes.rs")
    with open(out, "w") as f:
        f.write(HEADER + "\n" + body + func)
    print(f"wrote {os.path.abspath(out)}")


if __name__ == "__main__":
    main()
